# Generated by Django 3.1.2 on 2020-10-22 21:14

import auth_backend.modules.common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('code', models.CharField(default=auth_backend.modules.common.utils.generate_referral_code, max_length=255, unique=True, verbose_name='Referral Code')),
                ('role', models.SmallIntegerField(choices=[(0, 'Faculty'), (1, 'Student'), (2, 'Mentor')], verbose_name='Role')),
                ('is_used', models.BooleanField(default=False, help_text='Is referral code used', verbose_name='Is Used')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseVologUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('role', models.SmallIntegerField(choices=[(0, 'Faculty'), (1, 'Student'), (2, 'Mentor')], default=1, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False, help_text='for django reference', verbose_name='Staff status')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='Profile Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
