# Generated by Django 3.1.2 on 2020-10-16 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 10, 16, 10, 0, 6, 965193, tzinfo=utc), max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
