# Generated by Django 3.1.1 on 2020-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_referral_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevologuser',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Faculty'), (1, 'Student'), (2, 'Mentor')], null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Faculty'), (1, 'Student'), (2, 'Mentor')], null=True, verbose_name='Role'),
        ),
    ]
