# Generated by Django 3.1.1 on 2020-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourinstance',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Hours are penfing for aprooval'), ('APPROVED', 'Hours reported are aprooved'), ('DECLINED', 'Hours reported are declined')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='hourinstance',
            name='mentor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
