# Generated by Django 3.1.1 on 2020-10-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
