# Generated by Django 3.1.2 on 2020-10-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hour_sheet',
            field=models.OneToOneField(auto_created=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.timemaster'),
        ),
    ]
