# Generated by Django 3.1.1 on 2020-11-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_monthlyhourinstances_yearofstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyHourInstances',
        ),
        migrations.DeleteModel(
            name='YearOfStats',
        ),
    ]
