# Generated by Django 3.1.1 on 2020-11-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_2052'),
        ('api', '0002_bugreport_feedbackform'),
    ]

    operations = [
    ]
