# Generated by Django 3.1.2 on 2020-10-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201014_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hour_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timemaster'),
        ),
    ]
